
description: Software Engineer | Master's Student at UQ | Full Stack Developer
theme: minima
github_username: bardicbyte
linkedin_username: alvee-mir-b11322208
email: alveaahnaf25@gmail.com
baseurl: ""
url: "https://bardicbyte.github.io"

